/**
 * Probe Constants & IPC Message Enums
 */
export const IPC = {
  // Handshake & Mode
  PROBE_INIT: 'FIGR_PROBE_INIT',
  PROBE_ACK: 'FIGR_PROBE_ACK',
  SET_MODE: 'FIGR_SET_MODE',

  // Hit-Testing & Hover (R2)
  ELEMENT_HOVER: 'FIGR_ELEMENT_HOVER',
  ELEMENT_UNHOVER: 'FIGR_ELEMENT_UNHOVER',

  // Selection & Navigation (R3)
  ELEMENT_SELECT: 'FIGR_ELEMENT_SELECT',
  CLEAR_SELECTION: 'FIGR_CLEAR_SELECTION',
  KEYBOARD_NAV_REQ: 'FIGR_KEYBOARD_NAV_REQ',
  KEYBOARD_NAV_RESP: 'FIGR_KEYBOARD_NAV_RESP',

  // DOM Mutations & Scroll (R3, R4)
  DOM_MUTATED: 'FIGR_DOM_MUTATED',
  GEOMETRY_CHANGED: 'FIGR_GEOMETRY_CHANGED',
  PAGE_NAVIGATED: 'FIGR_PAGE_NAVIGATED',

  // Layers Tree Lazy Loading & Search (R4)
  QUERY_CHILDREN_REQ: 'FIGR_QUERY_CHILDREN_REQ',
  QUERY_CHILDREN_RESP: 'FIGR_QUERY_CHILDREN_RESP',
  QUERY_SEARCH_REQ: 'FIGR_QUERY_SEARCH_REQ',
  QUERY_SEARCH_RESP: 'FIGR_QUERY_SEARCH_RESP',
  SCROLL_INTO_VIEW: 'FIGR_SCROLL_INTO_VIEW',

  // Failure & Error Tracking (R6)
  PAGE_ERROR: 'FIGR_PAGE_ERROR',
};
